import BannerSection from '@/components/banner-section';

export default function TermsAndConditions() {
    return (
        <main>
            <BannerSection
                title={<>Terms & Conditions</>}
                image=""
            />

            <div className="py-20 bg-white">
                <div className="container">
                    <div className="prose !leading-[1.5]">
                        <p>These Terms of Service (“Terms of Service” or “ToS”) govern the use of the cannabis product ordering and delivery service that SD Technologies, Inc. (“Sweed” or “us” or “we”) makes available to an individual consumer (“you”) through our website located at www.sweedpos.com (the “Website”) and through mobile applications and related services, as modified from time to time (collectively, the “Service”). The Website and the Service are collectively and individually referred to as the “Solution”. As used in these ToS, the word “including” means “including without limitation”.</p>
                        <p>THESE TERMS OF SERVICE CONTAIN A BINDING ARBITRATION CLAUSE AND CLASS ACTION WAIVER THAT IMPACT YOUR RIGHTS IN RESOLVING DISPUTES.</p>
                        <p>By accessing or using the Solution, you expressly accept all of the provisions of these ToS and represent to us that you are an age legally permitted for ordering cannabis products for the state or province in which you are located, and that you are legally competent to enter into and agree to these ToS. If you do not accept these ToS, then you may not use the Solution.</p>
                        <h2>1. About Sweed; Acknowledgements</h2>
                        <p>A. What Sweed Does. Sweed provides a virtual service where consumers can connect with lawfully operated cannabis collectives, cooperatives, and related delivery service providers (collectively, “Dispensaries”). Sweed is not a Dispensary itself and is not a medical provider. You acknowledge that Sweed does not provide medical advice via the Solution or otherwise.</p>
                        <p>B. Dispensaries and State or Provincial Law. You may only place orders, make reservations, or request deliveries for goods or services at participating Dispensaries using the Solution. You must use the Solution , including the manner in which you order, reserve, request delivery, pick up and pay for products, in compliance with the laws and regulations of the state or province in which you access the Solution and all applicable federal laws, excepting only (if you are located in the United States) for federal laws and regulations related to marijuana (“Applicable Laws”). Depending on your location, payment for any goods or services may be made in-person at a Dispensary or authorized delivery location upon presenting your valid, government-issued identification, medical marijuana registration card, doctor’s recommendation, or such combination of the preceding documents or additional documents as may be required by Applicable Laws or the Dispensary. You agree and acknowledge that the features of the Solution may vary depending upon the state or province in which you access the Solution . For example, you may be able to request delivery of products in certain states or provinces, but not others.</p>
                        <p>C. Federal Law. Sweed makes no representation regarding the legality of the cultivation, manufacture, distribution and possession of marijuana, assisting with or conspiring to do the same, or any such activities by or through the Solution under United States federal law. You are responsible for any civil, criminal, or administrative investigations, proceedings or penalties that may result from Your use of the Solution. Sweed expressly disclaims any such liability or responsibility.</p>
                        <p>D. Product Descriptions. Sweed attempts to be as accurate as reasonably possible in product descriptions and images for products available through the Solution. However, Sweed is not a Dispensary and does not itself package, test, or label the products available through the Solution. Sweed does not warrant that product descriptions, images, or other content available through the Solution are accurate, complete, reliable, current, or error-free. You acknowledge and agree that that amounts in product descriptions through the Solution are averages or estimates, and that amounts may vary for individual items, packages, or orders that you receive. Amounts on the Website include, without limitation, the level (by weight, mass, volume, or percentage) of THC, CBD, other cannabinoids, and terpenes in a product, the total weight, mass, or volume of a product, the size, number of individual items, or services, in a product, and any other unit of measurement related to a product.</p>
                        <h2>2. Your Account</h2>
                        <p>A. Creating an Account. In order to create an account (“Account”) and become a registered user of the Service, you must have a valid government-issued ID and be of an age legally permitted for ordering cannabis products for the state or province in which you are located. You do not need to create an Account to use the Website, however, you will not be able to access certain features of the Website, place orders, make reservations, or request deliveries for products until you do so. You are responsible for providing us with and maintaining accurate contact information, including your name, email address, address, and phone number. If you intend to use the Solution to order medicinal marijuana, you must also provide us with your medical marijuana card or doctor’s recommendation. You represent that any information you provide to us is true and accurate.</p>
                        <p>B. Geolocation. In order to comply with state and provincial laws regarding the medical and/or recreational distribution, possession, and use of marijuana, Sweed must be able to obtain your approximate geographic location, via IP address lookup or otherwise. If you access the Website via a mobile device and disable location services on that device, or otherwise elect not to provide us with information regarding your location, you will not be able to access certain features of the Website, place orders, make reservations, or request deliveries for products. Additionally, certain features of the Website may not be available depending on your location.</p>
                        <p>C. Account Activities. You are the sole authorized user of your Account, and are responsible for maintaining the accuracy and confidentiality of your login information. You are solely and fully responsible for all activities that occur under your Account. Sweed has no control over the use of your or any other user’s Account. Sweed expressly disclaims any liability derived from misuse of any Account. Should you suspect that any unauthorized party may be using your Account or you suspect any other breach of security, you must cease all use of the Account and contact us immediately by emailing info@sweedpos.com.</p>
                        <p>D. Privacy Policy. Our practices regarding privacy and communicating with users in operating the Solution are described in our Privacy Policy. Please review our Privacy Policy to learn about what information we collect from you, how we use and share it, and how we communicate with our users. Our Privacy Policy can be accessed at: https://www.sweedpos.com/privacypolicy.</p>
                        <p>E. Messaging. By providing your mobile phone number and/or email address through the Solution or to a Dispensary, you expressly consent to receive informational and transactional messages at the mobile phone number and/or email address provided to Sweed and/or the Dispensary. Consent is not required as a condition of your use of the Solution . Standard per minute call and message and data rates may apply. You may opt-out of receiving marketing messages at any time.</p>
                        <h2>3. License And Restrictions; Ownership</h2>
                        <p>A. License Grant. Subject to your compliance with these ToS, we hereby grant you a personal, non-exclusive, non-transferable, revocable, limited license (without the right to sublicense) to access and use the Solution, for your personal use only, and subject to the limitations set forth in these ToS, including those in Section 3.C below. We reserve all rights not expressly granted to you pursuant to these ToS. The limited rights granted to you to access and use the Solution are a limited license and do not constitute the sale of any software program.</p>
                        <p>B. Fees. Sweed does not currently charge end users any fees for use of the Solution, although we reserve the right to do so in the future if permitted by Applicable Laws. Sweed will notify end users prior to charging any fees for use of the Solution.</p>
                        <p>C. Use Restrictions.</p>
                        <p>You agree that: (i) you will not use the Solution if you are not fully able and legally competent to agree to these ToS and of the required legal age; (ii) you willonly use the Solution in full compliance with Applicable Laws; (iii) you will not use the Solution for sending or storing any material prohibited by Applicable Law or for fraudulent purposes or to engage in any offensive, indecent or objectionable conduct; (iv) you will not use the Solution to advertise, solicit or transmit commercial advertisements, including “spam”; (v) you will not use the Solution to cause nuisance, annoyance or inconvenience; (vi) you will keep secure and confidential your account password or any identification we provide you which allows access to the Solution; and (vii) you will provide us with whatever proof of identity and other necessary verification documents as we may reasonably request.</p>
                        <p>Further, except as specifically permitted herein, you agree that you will not directly or indirectly: (i) distribute, sell, assign, encumber, transfer, rent, lease, loan, sublicense, modify, time-share or otherwise exploit the Solution in any unauthorized manner , including in any service bureau arrangement; (i i) copy, reproduce, adapt, create derivative works of, translate, localize, port or otherwise modify the Solution, or any part thereof in any form or manner or by any means; (iii) harvest or scrape any content or data from the Solution; (iv) remove or alter any copyright or other proprietary rights’ notice or restrictive rights legend contained or included in the Solution; (v) decompile, disassemble, reverse compile, reverse assemble, reverse translate, reverse engineer or otherwise use any means to discover the source code of any part of the Solution , or any part thereof (except as and only to the extent any foregoing restriction is prohibited by applicable law); (vi) otherwise circumvent any functionality that controls access to or otherwise protects the Solution; or (viii ) permit any third party to engage in any of the foregoing. Any attempt to do any of the foregoing is a violation of the rights of Sweed and its licensors. If you breach these restrictions, you may be subject to damages.</p>
                        <p>Ownership. The Solution and its content, including its “look and feel” (e.g., text, graphics, images, logos), proprietary content, information and other materials accessed through or on the Solution, including all right, title and interest in the same (including any and all patent, copyright, trade secret, trademark, know-how and any other intellectual property rights therein), are owned by Sweed and its licensors, and are protected under intellectual property, copyright, trademark and other laws. You agree not to take any action(s) inconsistent with such ownership interests.</p>
                        <p>D. Feedback and Revisions. Any and all: (i) suggestions for correction, change and modification to the Solution and other feedback (including but not limited to quotations of written or oral feedback), information and reports you provide to Sweed (collectively “Feedback”); and all (ii) improvements, updates, modifications or enhancements, whether made, created or developed by Sweed or otherwise relating to the Solution (collectively, “Revisions”), are and will remain the property of Sweed. You acknowledge and expressly agree that any contribution of Feedback or Revisions does not and will not give or grant you any right, title or interest in the Solution or in any such Feedback or Revisions. You agree that by providing Feedback or Revisions to Sweed that they become the sole and exclusive property of Sweed and Sweed may use and disclose Feedback and/or Revisions in any manner and for any purpose whatsoever without further notice or compensation to you. You hereby assign to Sweed any and all right, title and interest (including, but not limited to, any patent, copyright, trade secret, trademark, know-how, moral rights and any and all other intellectual property right) that you may have in and to any and all Feedback and Revisions.</p>
                        <p>E. User Content License Grant. The Solution may require you to rate (on a five star scale) each transaction you complete with a Dispensary using the Solution. You will also have the option to submit written feedback regarding the goods or services you received via such transaction. As a condition of your use of the Solution, you hereby grant to Sweed a nonexclusive, perpetual, irrevocable, royalty-free, worldwide, transferable, sublicensable license to access, use, reproduce, transmit, display, publish, distribute, modify and adapt and create derivative work from any content that you post, upload, publish, submit or transmit to be made available through the Solution (“Your Content”). By posting or submitting Your Content through the Solution, you represent and warrant: (i) that you own or otherwise control all of the rights to Your Content, including without limitation, all copyrights; (ii) that Your Content is accurate; and (iii) that use of Your Content does not violate these ToS or our Privacy Policy and will not cause injury to any person or entity. We take no responsibility and assume no liability for any content or materials submitted or posted through the Solution, including in the forums, by you or any third party. WE RESERVE THE RIGHT TO REMOVE ANY OF YOUR CONTENT THAT WE DETERMINE IN OUR SOLE DISCRETION VIOLATES ANY LAW, INFRINGES THE RIGHTS OF ANY PERSON, OR IS OTHERWISE INAPPROPRIATE FOR POSTING ON THE SOLUTION.</p>
                        <h2>4. Warranty Disclaimer</h2>
                        <p>THE SOLUTION IS PROVIDED TO YOU ON AN “AS IS” AND “AS AVAILABLE” BASIS, WITH ALL FAULTS AND WITHOUT WARRANTY OF ANY KIND, AND SWEED HEREBY EXPRESSLY DISCLAIMS ALL WARRANTIES, EXPRESS, IMPLIED OR STATUTORY, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE OR NON-INFRINGEMENT.</p>
                        <p>SWEED DOES NOT WARRANT THAT: (I) THE SOLUTION WILL MEET YOUR REQUIREMENTS; (II) OPERATION OF THE SOLUTION WILL BE UNINTERRUPTED OR VIRUS- OR ERROR-FREE; (III) THE SOLUTION WILL OPERATE OR BE COMPATIBLE WITH ANY OTHER APPLICATION OR ANY PARTICULAR SYSTEM OR DEVICE; OR (IV) DEFECTS IN THE SOLUTION CAN OR WILL BE CORRECTED.</p>
                        <p>SWEED DOES NOT WARRANT THE QUALITY, SAFETY, SUITABILITY, RELIABILITY OR AVAILABILITY OF ANY PRODUCTS, GOODS OR SERVICES OBTAINED BY YOU FROM DISPENSARIES OR OTHER PARTIES THROUGH THE SOLUTION. YOU ACKNOWLEDGE AND AGREE THAT, TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE ENTIRE RISK ARISING OUT OF YOUR USE OF PRODUCTS OR GOODS ORDERED VIA THE SOLUTION REMAINS SOLELY WITH YOU.</p>
                        <h2>5. Limitation of Liability.</h2>
                        <p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL SWEED BE LIABLE TO YOU OR ANY THIRD PARTY FOR LOSS OF PROFITS, REVENUE OR INCOME, OR FOR ANY INDIRECT, PUNITIVE, SPECIAL, EXEMPLARY, INCIDENTAL, OR CONSEQUENTIAL DAMAGES ARISING FROM OR RELATED TO THESE TOS OR THE USE OR INABILITY TO USE THE SOLUTION, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL SWEED’S TOTAL AGGREGATE LIABILITY UNDER THESE TOS, WHETHER BASED ON BREACH OF WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE) OR OTHERWISE, EXCEED THE GREATER OF: (I) THE AMOUNTS, IF ANY, YOU PAY TO SWEED UNDER THESE TERMS OR SERVICE; OR (II) ONE HUNDRED DOLLARS ($100) UNITED STATES DOLLARS.</p>
                        <h2>6. Indemnity</h2>
                        <p>By agreeing to these ToS and using the Solution, you agree, TO THE MAXIMUM EXTENT PERMITTED BY LAW, that you shall defend, indemnify and hold Sweed, its licensors and their respective parent organizations, subsidiaries, affiliates, officers, directors, members, employees, attorneys and agents harmless from and against any and all claims, costs, damages, losses, liabilities and expenses (including attorneys’ fees and costs) arising out of or in connection with: (i) your violation of any Applicable Laws; (ii) your violation of any rights of any third party; or (iii) your negligence or willful misconduct.</p>
                        <h2>7. Arbitration And Class Action Waiver.</h2>
                        <p>If you are using the Solution in the United States, the following arbitration clause applies:</p>
                        <p>Binding Arbitration. Any dispute or claim arising in any way from your use of the Solution, except for disputes relating to the infringement of our intellectual property rights , will be resolved by binding arbitration, rather than in court, but you may assert claims in small claims court if your claims qualify.</p>
                        <p>No Judge or Jury. There is no judge or jury in arbitration, and court review of an arbitration award is limited. However, an arbitrator can award on an individual basis the same damages and relief as a court (including injunctive and declaratory relief or statutory damages), and must follow the terms of these ToS as a court would.</p>
                        <p>Arbitrator and Rules. The arbitration will be conducted before a neutral single arbitrator, whose decision will be final and binding, and the arbitral proceedings shall be governed by the AAA Commercial Arbitration Rules, Consumer Due Process Protocol, and Supplementary Procedures for Resolution of Consumer Related Disputes. These rules can be found on the AAA website at www.adr.org.</p>
                        <p>Starting an Arbitration. To begin an arbitration proceeding, you must send us a notice of dispute, in writing, setting forth your name, address and contact information, the facts of the dispute and relief requested. You must send your notice of legal dispute to us at the following address: info@sweedpos.com. Sweed will send any notice of dispute to you at the contact information we have for you.</p>
                        <p>Format of Proceedings. The arbitration shall be conducted, at the option of the party seeking relief, by telephone, online, or based solely on written submissions.</p>
                        <p>Fees. If you initiate arbitration, your arbitration fees will be limited to the filing fee set forth in the AAA’s Consumer Arbitration Rules. Unless the arbitrator finds the arbitration was frivolous or brought for an improper purpose, Sweed will pay all other AAA and arbitrator’s fees and expenses.</p>
                        <p>Individual Basis. To the fullest extent permitted by applicable law, you and Sweed each agree that any dispute resolution proceeding will be conducted only on an individual basis and not in a class, consolidated or representative action. If for any reason a claim proceeds in court rather than in arbitration, you and Sweed each waive any right to a jury trial. As a result, PROCEEDINGS TO RESOLVE OR LITIGATE A DISPUTE IN ANY FORUM WILL BE CONDUCTED ONLY ON AN INDIVIDUAL BASIS.</p>
                        <p>Limitation Period. In no event shall any claim, action or proceeding by you or Sweed be instituted more than one (1) year after the cause of action arose.</p>
                        <p>Enforcement. Any judgment on the award rendered by the arbitrator may be entered in any court of competent jurisdiction. The United Nations Conventions on Contracts for the International Sale of Goods shall have no applicability.</p>
                        <p>Invalidity. If a court of competent jurisdiction finds the foregoing arbitration provisions invalid or inapplicable, you and Sweed each agree to the exclusive jurisdiction of the Federal and State courts located in the northern district of California, and you and Sweed each agree to submit to the exercise of personal jurisdiction of such courts for the purposes of litigating any applicable dispute or claim.</p>
                        <p>Opting Out. If you do not want to arbitrate disputes with Sweed and you are an individual, you may opt out of this arbitration agreement by sending an email to info@sweedpos.com within thirty (30) days of the first of the date you access or use the Solution.</p>
                        <h2>8. General Provisions</h2>
                        <p>Termination. If you breach any of the terms of these ToS, all licenses granted by us, including permission to use the Solution, will terminate automatically. Additionally, we may suspend, disable, or delete your Account, access to the Solution (or any part of the foregoing) with or without notice, for any or no reason (including, for example, if you fail to honor reservations you make through the Solution). If we delete your Account for any suspected breach of these ToS by you, you are prohibited from re-registering for the Solution under a different name. All sections which by their nature should survive the termination of these ToS shall continue in full force and effect subsequent to and notwithstanding any termination of this Agreement by Sweed or you. Termination will not limit any of our other rights or remedies at law or in equity.</p>
                        <p>Injunctive Relief. You agree that a breach of these ToS may cause irreparable injury to Sweed for which monetary damages might not be an adequate remedy and Sweed shall be entitled to seek equitable relief in addition to any remedies it may have hereunder or at law without a bond, other security or proof of damages.</p>
                        <p>Notices. We may give notice to you by means of a general notice on the Service or the Website, electronic mail, or by written communication sent by first class mail or pre-paid post. Such notice shall be deemed to have been given upon the expiration of 48 hours after mailing or posting (if sent by first class mail or pre-paid post) or 12 hours after sending (if sent by email). You may give notice to us (such notice shall be deemed given when received by us) at any time by sending an email to info@sweedpos.com. Please specify the reason for the email in the subject line so it can be forwarded to the proper department.</p>
                        <p>Miscellaneous. These ToS constitute the entire agreement between you and Sweed with respect to the subject matter hereof, and all prior or contemporaneous understandings or agreements, whether written or oral, between you and Sweed with respect to such subject matter are hereby superseded in their entirety. These ToS may not be modified except by a writing executed by the duly-authorized representatives of Sweed or pursuant to Section 8.5 of these ToS. No other act, document, usage or custom will be deemed to modify or amend these ToS. These ToS will inure to the benefit of and will be binding upon each party’s successors and assigns. These ToS and the licenses granted hereunder may be assigned by Sweed but may not be assigned by you without the prior express written consent of Sweed. Any attempt by you to assign these ToS without the written consent of Sweed shall be null and void. If any provision hereof is or becomes, at any time or for any reason, unenforceable or invalid, no other provision hereof will be affected thereby and the remaining provisions will continue with the same effect as if such unenforceable or invalid provisions will not have been inserted herein; provided that the ability of either party to obtain substantially the bargained-for performance of the other will not have thereby been impaired. It is expressly understood that in the event either party on any occasion fails to perform any term hereof and the other party does not enforce that term, the failure to enforce on any occasion will not constitute a waiver of any term and will not prevent enforcement on any other occasion. Nothing contained in these ToS will be deemed to constitute either party as the agent or representative of the other party or both parties as joint venturers or partners for any purpose. If either party is prevented from performing, or is unable to perform, any of its obligations under these ToS due to any cause beyond the reasonable control of the party invoking this provision, the affected party's performance will be extended for the period of delay or inability to perform due to such occurrence. The headings and captions contained herein will not be considered to be part of the ToS but are for convenience only. If you are using the Solution from the United States, the laws of the State of California, excluding its conflicts of law rules, govern these ToS and your use of the Service and the Website. If you are using the Solution from any other country, the laws of that country shall govern your use of the Solution. Your use of the Solution may also be subject to other local, state, provincial, or international laws.</p>
                        <p>Modifications. We may occasionally update these ToS. When we do so, we will post the updated ToS on the Website and revise the “Last Updated” date at the top of these ToS. If you continue to use the Solution after we post an update to these ToS, you indicate your acceptance of the updated ToS.</p>
                        <p>Contact Us. If you have any questions regarding these ToS or the Solution, please contact us at info@sweedpos.com.'</p>
                    </div>
                </div>
            </div>
        </main >
    )
}